### ISSUE TITLE
New vue 2.5.2 Unexpected token < when use compact

### ISSUE THREAD

**Issue by dinho-afsn** [xiaokaike/vue-color#93]
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
/Volumes/DESENVOLVIMENTO/node_modules/vue-color/src/components/Compact.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at r (/Volumes/DESENVOLVIMENTO/node_modules/nuxt/node_modules/vue-server-renderer/build.js:7758:16)
    at Object.<anonymous> (server-bundle.js:15618:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.330 (pages/Configuracoes/Institucionais.b672c0ed566403c98f65.js:217:95)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.327 (pages/Configuracoes/Institucionais.b672c0ed566403c98f65.js:140:414)
    at __webpack_require__ (server-bundle.js:27:30)

**Comment by linx4200** [comment]
Compact component works fine under Vue 2.5.2 on my computer. Could you provide more information for me to debug, for example your use cases? Thanks.

**Comment by linx4200** [comment]
I can't still reproduce the problem. If you encounter this problem again, please provide a reproducible demo, and reopen this issue. Thanks.
